BlogApp/urls.py
from django.urls import path
from . import views

app_name = 'BlogApp'

urlpatterns = [
    path('', views.blog, name='blog'),
    path('<int:blog_id>/', views.post, name='post'),
]

PersonalPortfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from PortfolioApp import views

app_name = 'PersonalPortfolio'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('blog/', include('BlogApp.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

BlogApp/models.py
from django.db import models

class Post(models.Model):
    subject = models.CharField(max_length=100)
    text = models.TextField(max_length=2000)
    datePosted = models.DateTimeField()
    def __str__(self):
        return self.subject

PortfolioApp/models.py
from django.db import models

class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=200)
    image = models.ImageField(upload_to='PersonalPortfolioApp/images/')
    url = models.URLField(blank=True)
    def __str__(self):
        return self.title

BlogApp/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Post

def blog(request):
    # posts = Post.objects.all()
    posts = Post.objects.order_by('-datePosted')
    return render(request, 'BlogApp/blog.html', {'posts':posts})

def post(request, blog_id):
    post = get_object_or_404(Post, pk=blog_id)
    return render(request, 'BlogApp/post.html', {'post':post})

PortfolioApp/views.py
from django.shortcuts import render
import random
from django.http import HttpResponse
from .models import Project

def home(request):
    projects = Project.objects.all()
    return render(request, 'PortfolioApp/home.html', {'projects':projects})

BlogApp/templates/blogapp/blog.html
{% extends 'PortfolioApp/base.html'%}

{% block content %}

<div class='container text-center'>
  <h1>Portfolio Blog</h1>
  </br>
  </br>
  <h5>There are currently {{ posts.count }} post{{ posts.count|pluralize }} in this blog.<h5>
  </br>
  {% for post in posts %}
    <a href='{% url 'BlogApp:post' post.id %}'><h3>{{ post.subject }}</h3></a>
    {{ post.datePosted}}
    </br>
    </br>
    <p>{{ post.text|striptags|truncatechars:100 }}</p>
  {% endfor %}
</div>

{% endblock %}

BlogApp/templates/blogapp/post.html
{% extends 'PortfolioApp/base.html'%}

{% block content %}

<div class='container text-center'>
  <h1>Portfolio Blog Post</h1>
  </br>
  </br>
  <h2>{{ post.subject }}</h2>
  {{ post.datePosted}}
  </br>
  </br>
  <p>{{ post.text|safe }}</p>
  </br>
  </br>
<div>

{% endblock %}

PortfolioApp/templates/PortfolioApp/base.html
<!doctype html>
<html lang="en">
  <head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel='stylesheet' href='https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap'>
    <link rel='stylesheet' href='{% static 'PortfolioApp/custom.css'%}'>
    <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Lato&display=swap'>
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel='icon' type='image/jpg' href='{% static 'PortfolioApp/Logo_1.jpg '%}'>
    <title>Dwight Johnson</title>
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>
  <body>
    <div class='container text-center'>
      <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <a class="navbar-brand" href="{% url 'home' %}">Dwight Johnson</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav ml-auto">
              <a class="nav-item nav-link" href="http://twitter.com/DwightJ37773086" target="_blank">Twitter</a>
              <a class="nav-item nav-link" href="{% static 'PortfolioApp/DDJ_20050731.pdf' %}">Resume</a>
              <a class="nav-item nav-link" href="{% url 'BlogApp:blog' %}">Blog</a>
            </div>
          </div>
        </nav>
      </header>
      <h1>Dwight's Personal Portfolio</h1>
    </div>

  {% block content %}{% endblock %}

    <div class='container text-center'>
          <footer class="text-muted">
              <p>© Dwight Johnson {% now "Y" %}</p>
          </footer>
          <!-- Bootstrap core JavaScript
          ================================================== -->
          <!-- Placed at the end of the document so the pages load faster -->
          <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
          <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
          <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </div>
  </body>
</html>

PortfolioApp/templates/PortfolioApp/home.html
{% extends 'PortfolioApp/base.html'%}

{% block content %}

<div class='container text-center'>
  {% load static %}
  </br>
  <section class="jumbotron text-center">
    <div class="container">
      <h1 class="jumbotron-heading">Hi, I'm Dwight.</h1>
      <p class="lead text-muted">Hey, my name is Dwight Johnson and I love to make Django websites!</p>
      <p>
        <a href="mailto:djohnson149@gmail.com" class="btn btn-primary my-2">Email Me</a>
      </p>
      <img src="{% static 'PortfolioApp/Dwight_closerup_2018.jpg' %}" height="200" />
    </div>
  </section>
  <!--  <img src='{% static 'PortfolioApp/Dwight_closerup_2018.jpg' %}' style="border:1px solid black; width: 50%, height: auto">
  -->
  {% for project in projects %}
    <h3>{{ project.title }}</h3>
    <p>{{ project.description }}</p>
  </br>
    {% if project.url %}
      <a href='{{ project.url }}'>
        <img src={{ project.image.url }} style="border:1px solid black; width: 50%, height: auto">
      </a>
    {% else %}
      <img src={{ project.image.url }} style="border:1px solid black; width: 50%, height: auto">
    {% endif %}
  {% endfor %}
</div>

{% endblock %}